<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-DJ4FDME" failures="2" tests="2" name="Test(failed)" time="0.127" errors="0" timestamp="2024-11-05T07:09:04 IST">
  <testcase classname="testNGDemo.TestScenarios2" name="third_testcase" time="0.036">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNGDemo.TestScenarios2.third_testcase(TestScenarios2.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- third_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="forth_testcase" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [Hello world] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello world] but found [Hello]
at testNGDemo.TestScenarios2.forth_testcase(TestScenarios2.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- forth_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
  <testcase classname="testNGDemo.TestScenarios2" name="first_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- first_testcase -->
</testsuite> <!-- Test(failed) -->
